/** Ghana delivery locations — keep in sync with App\Support\GhanaLocations. */

export const OTHER_CITY = 'Other city';

export const GHANA_REGION_ORDER = [
    'Greater Accra',
    'Ashanti',
    'Western',
    'Eastern',
    'Central',
    'Northern',
    'Upper East',
    'Upper West',
    'Volta',
    'Bono',
    'Western North',
    'Ahafo',
    'Bono East',
    'North East',
    'Savannah',
    'Oti',
] as const;

export const GHANA_CITIES_BY_REGION: Record<string, string[]> = {
    'Greater Accra': [
        'Abeka',
        'Ablekuma',
        'Accra',
        'Accra Central',
        'Achimota',
        'Adabraka',
        'Adenta',
        'Airport',
        'Amasaman',
        'Ashaiman',
        'Atomic',
        'Avenor',
        'Awoshie',
        'Baatsona',
        'Bubuashie',
        'Cantonments',
        'Chorkor',
        'Circle',
        'Dansoman',
        'Darkuman',
        'Dawhenya',
        'Dodowa',
        'Dome',
        'Dzorwulu',
        'East Legon',
        'Gbawe',
        'Haatso',
        'Jamestown',
        'Kanda',
        'Kaneshie',
        'Kasoa',
        'Kokomlemle',
        'Korle Bu',
        'Kwashieman',
        'Labadi',
        'Labone',
        'Lapaz',
        'Lashibi',
        'Legon',
        'Madina',
        'Makola',
        'Mallam',
        'Mamprobi',
        'Mataheko',
        'North Industrial Area',
        'North Kaneshie',
        'Nungua',
        'Ofankor',
        'Osu',
        'Oyarifa',
        'Pokuase',
        'Prampram',
        'Ridge',
        'Roman Ridge',
        'Sakumono',
        'Santa Maria',
        'South Industrial Area',
        'Spintex',
        'Spintex Road',
        'Tema',
        'Teshie',
        'Teshie Nungua',
        'Tesano',
        'Trasaco',
        'Tudu',
        'Usher Town',
        'Weija',
        OTHER_CITY,
    ],
    Ashanti: [
        'Abrepo',
        'Abuakwa',
        'Adum',
        'Afrancho',
        'Agogo',
        'Agona',
        'Ahafo Ano',
        'Ahinsan',
        'Ahodwo',
        'Airport Roundabout',
        'Amakom',
        'Asafo',
        'Asante Manpong',
        'Asokwa',
        'Atronsu',
        'Ayeduase',
        'Ayigya',
        'Bantama',
        'Bekwai',
        'Bomfa',
        'Adeduako',
        'Effiduase',
        'Ejisu',
        'Emena',
        'Fomena',
        'Jacobu',
        'Juaso',
        'Kentinkrono',
        'Konongo',
        'Kotei',
        'Kumasi',
        'Kwadaso',
        'Manpong',
        'Manso Nkwanta',
        'Nhyiaeso',
        'Nkawie',
        'Nsuta',
        'Obuasi',
        'Offinso',
        'Pankrono',
        'Tafo',
        'Tanoso',
        'Tech',
        'Tepa',
        'Toase',
        OTHER_CITY,
    ],
    Western: [
        'Aboadze',
        'Agona Nkwanta',
        'Asankragua',
        'Axim',
        'Bogoso',
        'Busua',
        'Dixcove',
        'Elubo',
        'Esiama',
        'Essikado',
        'Half Assini',
        'Huni Valley',
        'Mpohor',
        'Prestea',
        'Sekondi',
        'Shama',
        'Takoradi',
        'Tarkwa',
        'Wassa Akropong',
        OTHER_CITY,
    ],
    Eastern: [
        'Aburi',
        'Achiase',
        'Adukrom',
        'Akim Oda',
        'Akosombo',
        'Akropong',
        'Akwatia',
        'Akyem Hemang',
        'Amanokrom',
        'Asamankese',
        'Atimpoku',
        'Begoro',
        'Coaltar',
        'Effiduase',
        'Kibi',
        'Koforidua',
        'Kpong',
        'Mamfe',
        'Mpraeso',
        'New Tafo',
        'Nkawkaw',
        'Nkurakan',
        'Nsawam',
        'Oda',
        'Oyoko',
        'Somanya',
        'Suhum',
        OTHER_CITY,
    ],
    Central: [
        'Abakrampa',
        'Agona Swedru',
        'Ajumako',
        'Anomabo',
        'Apam',
        'Assin Fosu',
        'Awutu Bereku',
        'Bremen Asikuma',
        'Cape Coast',
        'Dominase',
        'Dunkwa-on-Offin',
        'Elmina',
        'Foso',
        'Gomoa',
        'Koaso',
        'Mankessim',
        'Mumford',
        'Nsuaem',
        'Nyakrom',
        'Saltpong',
        'Twifo Praso',
        'University of Cape Coast',
        'Winneba',
        'Yamoransa',
        OTHER_CITY,
    ],
    Northern: ['Tamale', 'Yendi', 'Savelugu', OTHER_CITY],
    'Upper East': [
        'Bawku',
        'Binduri',
        'Bolgatanga',
        'Bongo',
        'Garu',
        'Navrongo',
        'Paga',
        'Pusiga',
        'Pwalugu',
        'Telensi',
        'Tempane',
        'Tongo',
        'Zebilla',
        'Zuarungu',
        OTHER_CITY,
    ],
    'Upper West': ['Wa', 'Lawra', 'Nandom', 'Jirapa', OTHER_CITY],
    Volta: ['Ho', 'Hohoe', 'Keta', 'Aflao', 'Kpandu', OTHER_CITY],
    Bono: ['Sunyani', 'Berekum', 'Dormaa Ahenkro', 'Wenchi', OTHER_CITY],
    'Western North': [
        'Akontombra',
        'Anhwinso',
        'Asawinso',
        'Bia',
        'Bibiani',
        'Bodi',
        'Chirano',
        'Dadieso',
        'Debiso',
        'Enchi',
        'Juaboso',
        'Sefwi Awaso',
        'Sefwi Bekwai',
        'Sefwi Wiawso',
        OTHER_CITY,
    ],
    Ahafo: [
        'Acherensua',
        'Bechem',
        'Duayaw Nkwanta',
        'Goaso',
        'Hwidiem',
        'Kenyase',
        'Kukuom',
        'Mim',
        'Noberkwa',
        'Sankore',
        'Yamfo',
        OTHER_CITY,
    ],
    'Bono East': [
        'Abease',
        'Amantin',
        'Atebubu',
        'Babatokuma',
        'Jema',
        'Kintampo',
        'Kwame Danso',
        'New Longoro',
        'Nkoranza',
        'Nsuta',
        'Prang',
        'Techiman',
        'Tuobodom',
        'Yeji',
        OTHER_CITY,
    ],
    'North East': [
        'Bunkpurugu',
        'Chereponi',
        'Demon',
        'Gambaga',
        'Jimbale',
        'Nakpanduri',
        'Nalerigu',
        'Walewale',
        'Wenchiki',
        'Yunyoo',
        OTHER_CITY,
    ],
    Savannah: [
        'Bole',
        'Buipe',
        'Canteen',
        'Daboya',
        'Damongo',
        'Gbintiri',
        'Grupe',
        'Kalande',
        'Lungbunga',
        'Salaga',
        'Sawla',
        'Tuna',
        'Yapei',
        OTHER_CITY,
    ],
    Oti: [
        'Akpafu',
        'Brewaniase',
        'Chinderi',
        'Dambai',
        'Jasikan',
        'Kate krachi',
        'Kpassa',
        'Krachi Nchumuru',
        'Kwamekrom',
        'Likpe',
        'Lolobi',
        'Nkwanta',
        'Santrokofi',
        'Worawora',
        OTHER_CITY,
    ],
};

export const GHANA_REGIONS = [
    ...GHANA_REGION_ORDER.filter((region) => region in GHANA_CITIES_BY_REGION),
    ...Object.keys(GHANA_CITIES_BY_REGION).filter((region) => !GHANA_REGION_ORDER.includes(region as (typeof GHANA_REGION_ORDER)[number])),
];

export function citiesForRegion(region: string): string[] {
    return GHANA_CITIES_BY_REGION[region] ?? [];
}
